version: '3'

env:
  ENV: prototyping

dotenv: ['.env']


tasks:
  select:
    desc: "🔧 Root menu: Choose domain to explore tasks"
    silent: true
    cmds:
      - |
        DOMAIN=$(echo -e "nats\nlogging\ndocker\ndev" | gum choose)
        case "$DOMAIN" in
          nats) task select:nats ;;
          logging) task select:logging ;;
          docker) task select:docker ;;
          dev) task select:dev ;;
        esac
  select:logging:
    desc: "🪵 Select a logging task"
    silent: true
    cmds:
      - |
        CHOICE=$(grep '^  logging_' Taskfile.yml | cut -d: -f1 | sed 's/^  //' | gum choose)
        task "$CHOICE"

  # --- SELECTOR ZONES ---

  select:nats:
    desc: "🧠 Select a NATS task"
    silent: true
    cmds:
      - |
        CHOICE=$(grep '^  nats_' Taskfile.yml | cut -d: -f1 | sed 's/^  //' | gum choose)
        task "$CHOICE"

  select:docker:
    desc: "🐳 Select a Docker task"
    silent: true
    cmds:
      - |
        CHOICE=$(grep '^  docker_' Taskfile.yml | cut -d: -f1 | sed 's/^  //' | gum choose)
        task "$CHOICE"

  select:dev:
    desc: "🛠️ Select a Dev task"
    silent: true
    cmds:
      - |
        CHOICE=$(grep '^  dev_' Taskfile.yml | cut -d: -f1 | sed 's/^  //' | gum choose)
        task "$CHOICE"

  default:
    desc: "📂 (Default) Run the domain/task selector"
    cmds:
      - task: select

  # --- NATS TASKS ---
  nats_restart:
    desc: "🔁 Restart NATS and ping"
    cmds:
      - task docker_nats_down
      - task nats_render_conf
      - task docker_nats_up

  nats_ping:
    desc: "🔁 Restart NATS and ping"
    cmds:
      - echo "Pinging NATS using ${NATS_SYS_USER} and ${NATS_SYS_USER_PASSWORD} at ${NATS_HOST}:${NATS_PORT}"
      - nats --user ${NATS_SYS_USER} --password ${NATS_SYS_USER_PASSWORD} server info --server ${NATS_HOST}:${NATS_PORT}

  nats_restart_and_ping:
    desc: "🔁 Restart NATS and ping"
    cmds:
      - task nats_restart
      - task nats_ping

  # --- MESSAGING TASKS ---


  # --- DOCKER TASKS ---

  docker_all_up:
    desc: "🚀 Bring all Docker services up"
    cmds:
      - task: docker_nats_up
      - task: docker_logging_stout_up

  docker_all_down:
    desc: "🛑 Bring all Docker services down"
    cmds:
      - task: docker_nats_down
      - task: docker_logging_stout_down

  docker_nats_down:
    desc: "🛑 Stop NATS container"
    cmds:
      - docker compose -f infra/docker-compose.yml stop nats

  docker_nats_up:
    desc: "🚀 Start NATS container"
    cmds:
      - task: nats_render_conf
      - docker compose -f infra/docker-compose.yml up -d nats

  docker_logging_stout_up:
    desc: "🚀 Start logging_stout container"
    cmds:
      - task: logging_stout_render_conf
      - docker compose -f infra/docker-compose.yml up -d logging_stout

  docker_nuke:
    desc: "💣 Stop and remove all Docker containers, volumes, and networks"
    cmds:
      - |
        echo "WARNING: This will nuke all Docker containers, volumes, and networks related to this project."
        read -p "Are you absolutely sure? (type 'nuke' to confirm): " CONFIRM
        if [ "$CONFIRM" = "nuke" ]; then
          docker compose -f infra/docker-compose.yml down -v --remove-orphans
          docker container prune -f
          docker network prune -f
        else
          echo "Aborted."
        fi


  # --- Dev Ops ---
  load_env:
    desc: "🔐 Load environment variables from .env"
    silent: true
    cmds:
      - |
          set -a
          source .env
          set +a

  render_template:
    desc: "🛠️ Render a template file using envsubst"
    summary: "Usage: task render_template SOURCE=... DEST=..."
    silent: true
    requires:
      vars: ["SOURCE", "DEST"]
    cmds:
      - |
        envsubst < "{{.SOURCE}}" > "{{.DEST}}"
        echo
        echo -e "\033[92mrendered {{.DEST}}\033[0m"

  nats_render_conf:
    desc: "📄 Render NATS config from template"
    cmds:
      - task: render_template
        vars:
          SOURCE: "infra/nats/nats.template.conf"
          DEST:   "infra/nats/nats.conf"

  logging_stout_render_conf:
    desc: "📄 Render logging_stout config from template"
    cmds:
      - task: render_template
        vars:
          SOURCE: "domains/logging_stout/config.template.ts"
          DEST:   "domains/logging_stout/config.ts"

  # --- Dev ---

  dev_mock_emit_once:
    desc: "📤 Emit a single mock event"
    cmds:
      - npx ts-node tools/mock-emmiter.ts

  dev_mock_emit_loop:
    desc: "🔁 Emit mock events repeatedly"
    cmds:
      - while true; do npx ts-node tools/mock-emmiter.ts; sleep 1; done
   
  dev_env_test:
    desc: "Testing environment variables"
    silent: true
    cmds:
      - echo ${NATS_SYS_USER}
  docker_logging_stout_down:
    desc: "🛑 Stop logging_stout container"
    cmds:
      - docker compose -f infra/docker-compose.yml stop logging_stout
  dev_kill_4222:
    desc: "🧨 Kill whatever process is using port 4222"
    cmds:
      - |
        echo "Checking for process on port 4222..."
        lsof -i :4222 || echo "No output from lsof"
        PID=$(lsof -ti :4222)
        echo "Resolved PID: $PID"
        if [ -n "$PID" ]; then
          echo "Attempting to kill process $PID"
          kill -9 $PID
          echo "Process $PID killed."
        else
          echo "No process found on port 4222."
        fi


