version: '3'

env:
  ENV: prototyping

dotenv: ['.env']


tasks:
  select:
    desc: "🔧 Root menu: Choose domain to explore tasks"
    silent: true
    cmds:
      - |
        DOMAIN=$(echo -e "nats\ndocker\ndev" | gum choose)
        case "$DOMAIN" in
          nats) task select:nats ;;
          docker) task select:docker ;;
          dev) task select:dev ;;
        esac

  # --- SELECTOR ZONES ---

  select:nats:
    desc: "🧠 Select a NATS task"
    silent: true
    cmds:
      - |
        CHOICE=$(grep '^  nats_' Taskfile.yml | cut -d: -f1 | sed 's/^  //' | gum choose)
        task "$CHOICE"

  select:docker:
    desc: "🐳 Select a Docker task"
    silent: true
    cmds:
      - |
        CHOICE=$(grep '^  all_' Taskfile.yml | cut -d: -f1 | sed 's/^  //' | gum choose)
        task "$CHOICE"

  select:dev:
    desc: "🛠️ Select a Dev task"
    silent: true
    cmds:
      - |
        CHOICE=$(grep '^  dev_' Taskfile.yml | cut -d: -f1 | sed 's/^  //' | gum choose)
        task "$CHOICE"

  default:
    desc: "📂 (Default) Run the domain/task selector"
    cmds:
      - task: select

  # --- NATS TASKS ---
  nats_restart:
    desc: "🔁 Restart NATS and ping"
    cmds:
      - task docker_nats_down
      - task nats_render_conf
      - task docker_nats_up

  nats_ping:
    desc: "🔁 Restart NATS and ping"
    cmds:
      - echo "Pinging NATS using ${NATS_SYS_USER} and ${NATS_SYS_USER_PASSWORD} at ${NATS_HOST}:${NATS_PORT}"
      - nats --user ${NATS_SYS_USER} --password ${NATS_SYS_USER_PASSWORD} server info --server ${NATS_HOST}:${NATS_PORT}

  nats_restart_and_ping:
    desc: "🔁 Restart NATS and ping"
    cmds:
      - task nats_restart
      - task nats_ping

  # --- MESSAGING TASKS ---


  # --- DOCKER TASKS ---

  all_up:
    desc: "🚀 Bring all Docker services up"
    cmds:
      - docker compose -f infra/docker-compose.yml up -d

  all_down:
    desc: "🛑 Bring all Docker services down"
    cmds:
      - docker compose -f infra/docker-compose.yml down

  docker_nats_down:
    desc: "🛑 Stop NATS container"
    cmds:
      - docker compose -f infra/docker-compose.yml stop nats

  docker_nats_up:
    desc: "🚀 Start NATS container"
    cmds:
      - docker compose -f infra/docker-compose.yml up -d nats


  # --- Dev Ops ---
  load_env:
    desc: "🔐 Load environment variables from .env"
    silent: true
    cmds:
      - |
          set -a
          source .env
          set +a

  render_template:
    desc: "🛠️ Render a template file using envsubst"
    summary: "Usage: task render_template SOURCE=... DEST=..."
    silent: true
    requires:
      vars: ["SOURCE", "DEST"]
    cmds:
      - |
        envsubst < "{{.SOURCE}}" > "{{.DEST}}"
        echo
        echo -e "\033[92mrendered {{.DEST}}\033[0m"

  nats_render_conf:
    desc: "📄 Render NATS config from template"
    cmds:
      - task: render_template
        vars:
          SOURCE: "infra/nats/nats.template.conf"
          DEST:   "infra/nats/nats.conf"

  # --- Dev ---

  dev_mock_emit_once:
    desc: "📤 Emit a single mock event"
    cmds:
      - npx ts-node tools/mock-emmiter.ts

  dev_mock_emit_loop:
    desc: "🔁 Emit mock events repeatedly"
    cmds:
      - while true; do npx ts-node tools/mock-emmiter.ts; sleep 1; done
   
  dev_env_test:
    desc: "Testing environment variables"
    silent: true
    cmds:
      - echo ${NATS_SYS_USER}