name: mu3
services:
  nats:
    image: nats
    ports:
      - "${NATS_PORT:-4222}:4222"
    restart: unless-stopped
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf:ro
    command: ["-c", "/etc/nats/nats.conf"]
    environment:
      - NODE_ENV=${NODE_ENV}

  logging_stout:
    build:
      context: ../
      dockerfile: domains/logging_stout/dockerfile
    restart: unless-stopped
    working_dir: /mu3/app
    volumes:
      - ../domains/logging_stout:/mu3/app
      - ../domains/shared:/mu3/shared
    environment:
      - NODE_ENV=${NODE_ENV}
    command: npm run dev