name: mu3
services:
  nats:
    image: nats
    ports:
      - "${NATS_PORT:-4222}:4222"
    restart: unless-stopped
    volumes:
      - ./nats/nats.conf:/etc/nats/nats.conf:ro
    command: ["-c", "/etc/nats/nats.conf"]
    environment:
      - NODE_ENV=${NODE_ENV}
  logging_stout:
    build:
      context: ../domains/logging/stout
    restart: unless-stopped
    working_dir: /app
    environment:
      - NODE_ENV=${NODE_ENV}