# syntax=docker/dockerfile:1
FROM node:22-alpine

# Set working directory
WORKDIR /app

# Copy and install dependencies
COPY package*.json ./
RUN npm install

# Copy source
COPY . .


# Default command: run the TS entry point directly
CMD ["npx", "ts-node", "--transpile-only", "services/index.ts"]
